[package]
name = "hello-bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
cgmath = "0.18.0"
iyes_perf_ui = "0.2.3"
noise = "0.9.0"
smooth-bevy-cameras = "0.11.0"

[profile.release]
opt-level = 3
