[package]
name = "hello-bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
bevy_fps_controller = "0.2.5"
bevy_mod_raycast = "0.17.0"
bevy_rapier3d = "0.25.0"
cgmath = "0.18.0"
iyes_perf_ui = "0.2.3"
noise = "0.9.0"

[profile.release]
opt-level = 3
