name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable  
    - name: Install dependencies
      run: sudo apt-get install -y -qq libasound2-dev libssl-dev libpulse-dev libdbus-1-dev portaudio19-dev 
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
